- name: configure cart server
  hosts: cart
  become: yes

  tasks:
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: Create system cart
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name: delete a app directory if it does exist
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete zip file if it does exist
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent
  
  - name: Download cart code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: Unarchive 
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: Install packages based on package.json.
    community.general.npm:
      path: /app
  
  - name: copy cart service
    ansible.builtin.template:
      src: cart.service
      dest: /etc/systemd/system/cart.service
  
  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start service cart, if not started
    ansible.builtin.service:
      name: cart 
      state: restarted
      enabled: yes

