- name: configure catalogue service
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: Create a system user roboshop
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      shell: /sbin/nologin
      comment: "roboshop system user"
  
  - name: delete a app directory if it does exist
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create a app directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: delete zip file if it does exist
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: Download catalogue code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: Unarchive 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install packages based on package.json.
    community.general.npm:
      path: /app
  
  - name: copy catalogue service
    ansible.builtin.template:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: copy mongo repo
    ansible.builtin.template:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present
  
  - name: check products loaded or not
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalaogue_output

  - name: print output
    ansible.builtin.debug:
      msg: "{{ catalaogue_output }}"
  
  - name: load products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalaogue_output.stdout | int < 0

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start service catalogue, if not started
    ansible.builtin.service:
      name: catalogue 
      state: restarted
      enabled: yes
